name: 'Test Local Action'

on:
  workflow_dispatch:
    inputs:
      commitish:
        description: 'Commitish'
        type: string
        required: true
        default: 'master'
      tag_name:
        description: 'Tag'
        type: string
        required: true
        default: 'v0.1.0'
      prerelease:
        description: 'PreRelease'
        type: boolean
        required: true
        default: false

jobs:
  test-local-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Test local action'
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commitish: ${{ inputs.commitsh }}
          tag_name: ${{ inputs.tag_name }}
          prerelease: ${{ inputs.prerelease }}
